services:
  authorization-server:
    image: ghcr.io/zhijun-io/rose-authorization-server:latest
    ports:
      - "9000:9000"
    volumes:
      - ../configs/config.yml:/config/config.yml:ro
    command:
      - --config=/config/config.yml
