name: Docker Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  image:
    permissions:
      contents: read
      packages: write
    uses: zhijun-io/github-workflows/.github/workflows/docker-build.yml@main
    with:
      push: true
      tags: 'latest,0.1.0'
